# STAGE 1 (where we have slim image with linux distribution)

FROM python:3.10-slim AS build

WORKDIR /workspace

COPY . .

RUN pip install -r requirements.txt --target=/workspace/deps

# Stage 2 (Just have the code and the code dependencies without any distribution)

FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=build /workspace/deps /app/deps
COPY --from=build /workspace .

ENV PYTHONPATH="/app/deps"

EXPOSE 5000

CMD ["app.py"]
